#include "splash.h"
#include "epd_driver.h"
#include "app_config.h"

#include "esp_log.h"

static const char *TAG = "splash";

/* Symbols injected by CMake's EMBED_FILES: see src/CMakeLists.txt.
 * Generated by tools/gen_splash.py; rebuilt offline (committed under assets/). */
extern const uint8_t splash_logo_bin_start[]   asm("_binary_splash_logo_bin_start");
extern const uint8_t splash_logo_bin_end[]     asm("_binary_splash_logo_bin_end");
extern const uint8_t splash_portal_bin_start[] asm("_binary_splash_portal_bin_start");
extern const uint8_t splash_portal_bin_end[]   asm("_binary_splash_portal_bin_end");

static esp_err_t paint(const uint8_t *start, const uint8_t *end, const char *label)
{
    size_t len = (size_t)(end - start);
    if (len != EPD_BUF_BYTES) {
        ESP_LOGE(TAG, "%s blob is %u bytes, expected %u; refusing to paint",
                 label, (unsigned)len, (unsigned)EPD_BUF_BYTES);
        return ESP_ERR_INVALID_SIZE;
    }
    esp_err_t err = epd_port_init();
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "epd_port_init failed (%d); skipping %s splash", err, label);
        return err;
    }
    ESP_LOGI(TAG, "painting %s splash (~30 s)...", label);
    /* epd_display() runs the full panel init + DTM + PON + DRF + POF + DSLP
     * cycle internally on this firmware; no separate epd_init() needed. */
    epd_display(start);
    epd_sleep();
    return ESP_OK;
}

esp_err_t splash_show_logo(void)
{
    return paint(splash_logo_bin_start, splash_logo_bin_end, "logo");
}

esp_err_t splash_show_portal(void)
{
    return paint(splash_portal_bin_start, splash_portal_bin_end, "portal");
}
